### ISSUE TITLE
Display cursor

### ISSUE THREAD

**Issue by barnumbirr** [ichub/tply#1]
Hi there,

wanted to know if it would be possible to display the cursor while typing?
Thank you for this awesome lib.

Cheers.

**Comment by ichub** [comment]
Thanks for the suggestion, having a cursor is something a few people have asked for, so I'll get around to implementing it soon.

**Comment by ichub** [comment]
Alright, I've added cursors. Check them out on the demo page: https://ichub.github.io/tply/
